pool:
  vmImage: 'ubuntu-latest'

trigger:
  paths:
    include:
      - src/EdgeModules/VideoCapture
      - pipelines/build-video-capture.yaml      


variables:
 ${{ if eq( variables['Build.SourceBranchName'], 'main') }}:
  major: 0
  minor: 0
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 1)]
  version: '$(major).$(minor).$(patch)'
 ${{ else }}:
  patch: $[counter(variables['Build.SourceBranchName'],1)
  version: $(Build.SourceBranchName)-$(patch)

steps:
- template: build-edge-module.yaml
  parameters:
    containerRegistry: 'catcamacr-dev'
    repository: 'video-capture'
    dockerFile: 'src/EdgeModules/VideoCapture/Dockerfile.amd64'
    context: 'src/EdgeModules/VideoCapture'
    tag: '$(version)-amd64'

- template: build-edge-module.yaml
  parameters:
    containerRegistry: 'catcamacr-dev'
    repository: 'video-capture'
    dockerFile: 'src/EdgeModules/VideoCapture/Dockerfile.arm32v7'
    context: 'src/EdgeModules/VideoCapture'
    tag: '$(version)-arm32v7'