pool:
  vmImage: 'ubuntu-latest'

trigger:
  paths:
    include:
      - src/EdgeModules/VideoCapture
      - pipelines/build-video-capture.yaml      

steps:
- task: Docker@2
  displayName: Docker Build of Video Capture module amd64
  inputs:
    containerRegistry: 'catcamacr-dev'
    repository: 'video-capture'
    command: 'build'
    Dockerfile: 'src/EdgeModules/VideoCapture/Dockerfile.amd64'
    buildContext: 'src/EdgeModules/VideoCapture'
    tags: 'amd64-latest'

- task: Docker@2
  displayName: Docker Push of Video Capture module
  inputs:
    containerRegistry: 'catcamacr-dev'
    repository: 'video-capture'
    command: 'push'
    tags: 'amd64-latest'

- task: Docker@2
  displayName: Docker Build of Video Capture module arm32
  inputs:
    containerRegistry: 'catcamacr-dev'
    repository: 'video-capture'
    command: 'build'
    Dockerfile: 'src/EdgeModules/VideoCapture/Dockerfile.arm32v7'
    buildContext: 'src/EdgeModules/VideoCapture'
    tags: 'arm32-latest'

- task: Docker@2
  displayName: Docker Push of Video Capture module
  inputs:
    containerRegistry: 'catcamacr-dev'
    repository: 'video-capture'
    command: 'push'
    tags: 'arm32-latest'    