FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

# RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install --extra-index-url=https://www.piwheels.org/simple  --only-binary=:all: -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]