FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish EdgeModules/VideoCaptureSharp/src -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "VideoCaptureSharp.dll"]