FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore EdgeModules/FileWatcher/src -r linux-arm
RUN dotnet publish EdgeModules/FileWatcher/src -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:7.0-bullseye-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

# RUN useradd -ms /bin/bash moduleuser
# USER moduleuser
# Fails on cross platform - test module without user

ENTRYPOINT ["dotnet", "FileWatcher.dll"]